### ISSUE TITLE
Update mongo gem

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluent-plugin-mongo#36]
Lastest MongoDB has a bug with current specified mongo gem on replica set environment?

Japanese article about this problem: http://qiita.com/kikunaga0719/items/7e604058e542ec43fb67

**Comment by fetaro** [comment]
Because Ruby-MongoDB-driver before 1.8.6 has limitation about documents size.
Therefore, when fluent-plugin-mongo try to insert a amount of documents into MongoDB, raise error "Exceded maximum insert size of xxx".

Ruby-MongoDB-driver after 1.9.0 can handle large amount of documents by splitting insert.
See https://jira.mongodb.org/browse/RUBY-533
