### ISSUE TITLE
number was saved as String

### ISSUE THREAD

**Issue by passos** [fluent/fluent-plugin-mongo#58]
If I send a log from a Java client like this:

    dataLogger.log("access", new HashMap<String, Object>() {{
                put("uri", request.getRequestURI());
                put("timestamp", System.currentTimeMillis());
            }});

The "timestamp" field's value in MongoDB is actually saved as String instead of Number. Is there any option to make it to Number?

**Comment by repeatedly** [comment]
It because JSON/MessagePack doesn't have timestamp format.
How about using 3 arguments version of log method to specify timestamp?

https://github.com/fluent/fluent-logger-java/blob/ea176c24f2a05bcc842c156675e00a8fd349a39c/src/main/java/org/fluentd/logger/FluentLogger.java#L89

Do you want to store Fluentd's event time and timestamp separately?

**Comment by passos** [comment]
em, thanks. I just found that it's actually my mistake.

I make a HashMap<String, String> to store log data, use Gson to convert it to JSON format, post it to server from mobile client, then restore the Map from this JSON String and use this map in fluentd logger.

The problem is the original Map's type is <String, String> instead of <String, Object> so that the number is presented as String when it is converted to JSON string.

The code I post in the question actually works correctly.
